Output gifs/motions-langmapper.gif

Set Shell "bash"
Set FontFamily "JBMonoNL Demo Light"
Set LineHeight 1.55
Set FontSize 15
Set Width 1200
Set Height 604
Set Padding 0
Set Theme "Catppuccin Macchiato"
Set TypingSpeed 150ms
Set Framerate 24

Hide
Type "export XDG_CONFIG_HOME=$PWD/profile/config XDG_DATA_HOME=$PWD/profile/data XDG_STATE_HOME=$PWD/profile/state XDG_CACHE_HOME=$PWD/profile/cache"
Enter
Type "cd work && DEMO_EXTRAS=motions.langmapper nvim app.lua"
Enter
Sleep 14s
Show
Sleep 2s
Type "ооо"
Sleep 1500ms
Type "ддд"
Sleep 1500ms
Type "вв"
Sleep 2s
Type "г"
Sleep 2500ms
Hide
Type ":qa!"
Enter
