Output gifs/ui-better-insert-mode.gif

Set Shell "bash"
Set FontFamily "JBMonoNL Demo Light"
Set LineHeight 1.55
Set FontSize 15
Set Width 1200
Set Height 604
Set Padding 0
Set Theme "Catppuccin Macchiato"
Set TypingSpeed 150ms
Set Framerate 24

Hide
Type "export XDG_CONFIG_HOME=$PWD/profile/config XDG_DATA_HOME=$PWD/profile/data XDG_STATE_HOME=$PWD/profile/state XDG_CACHE_HOME=$PWD/profile/cache"
Enter
Type "cd work && DEMO_EXTRAS=ui.better-insert-mode,ui.better-colorcolumn nvim app.lua"
Enter
Sleep 12s
Type "5G"
Sleep 1s
Show
Sleep 2500ms
Type "i"
Sleep 3s
Escape
Sleep 3s
Hide
Type ":qa!"
Enter
