Output gifs/ui-better-explorer.gif
Output videos/ui-better-explorer.mp4

Set Shell "bash"
Set FontFamily "JBMonoNL Demo Light"
Set LineHeight 1.55
Set FontSize 15
Set Width 1200
Set Height 766
Set Padding 0
Set Theme "Catppuccin Macchiato"
Set TypingSpeed 150ms
Set Framerate 24

Hide
Type "export XDG_CONFIG_HOME=$PWD/profile/config XDG_DATA_HOME=$PWD/profile/data XDG_STATE_HOME=$PWD/profile/state XDG_CACHE_HOME=$PWD/profile/cache"
Enter
Type "cd work/project && DEMO_EXTRAS=ui.better-explorer nvim app.lua"
Enter
Sleep 14s
Show
Sleep 1500ms
Space
Type "fy"
Sleep 4s
Type "j"
Sleep 1s
Type "j"
Sleep 1500ms
Enter
Sleep 3s
Hide
Type ":qa!"
Enter
